# Generated by Django 4.2.6 on 2023-10-30 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
