# Generated by Django 4.2.6 on 2023-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunc', '0002_document_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
    ]
