# Generated by Django 4.2.6 on 2023-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunc', '0003_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=500),
        ),
    ]
