# Generated by Django 4.2.6 on 2023-10-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunc', '0004_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
