# Generated by Django 4.2.7 on 2023-11-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunc', '0005_remove_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_created',
        ),
    ]
