# Generated by Django 4.2.6 on 2023-11-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('docID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermDocumentMatrix',
            fields=[
                ('termID', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('docID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdm.documents')),
            ],
        ),
    ]
