# Generated by Django 4.2.6 on 2023-11-02 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
