# Generated by Django 4.2.6 on 2023-11-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0002_documents_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='overview',
            field=models.CharField(default='Unknown Title', max_length=150),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=100),
        ),
    ]
