# Generated by Django 4.2.7 on 2023-11-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0003_documents_overview_alter_documents_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='date_created',
        ),
    ]
