# Generated by Django 4.2.7 on 2023-11-03 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0004_remove_documents_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
