# Generated by Django 4.2.7 on 2023-11-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0005_documents_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='date_created',
        ),
    ]
