# Generated by Django 4.2.7 on 2023-11-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0006_remove_documents_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.DeleteModel(
            name='TermDocumentMatrix',
        ),
    ]
