# Generated by Django 4.2b1 on 2023-11-18 20:22

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0007_rename_documents_document_delete_termdocumentmatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docID',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
