# Generated by Django 4.2b1 on 2023-11-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0008_alter_document_docid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docID',
            new_name='_id',
        ),
    ]
