# Generated by Django 4.2b1 on 2023-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0009_rename_docid_document__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='_id',
        ),
        migrations.AddField(
            model_name='document',
            name='docID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
