# Generated by Django 4.2b1 on 2023-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0010_remove_document__id_document_docid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
